baseURL = "/"
languageCode = "en-us"
title = "lej.site"
enableEmoji = true
publishDir = "docs"

theme = "anatole"

[params]
displayMode = "dark"
disableThemeSwitcher = true
mainSections = ["about", "work", "non-work"]
title = "Hi, I'm Lejia"
author = "ljdn"
description = "I write code | Bay Area"
profilePicture = "images/profile_circle.png"
disableKinds = ["taxonomy", "taxonomyTerm"]
doNotLoadAnimations = true

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/lejiaduan/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/ljdn"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:lejia.duan@gmail.com"

[menu]

  [[menu.main]]
  name = "/about"
  identifier = "about"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "/work"
  weight = 200
  identifier = "work"
  url = "/work"

  [[menu.main]]
  name = "/site"
  weight = 300
  identifier = "site"
  url = "/site"
